// src/views/Home.vue
<template>
  <div class="home">
    <h1>Track Your Watch Activity</h1>
    <p>Start by searching for a show or movie above.</p>
  </div>
</template>

<script>

export default {
  name: 'Home',
  data() {
    return {
    };
  },
  methods: {
  },
};
</script>

<style scoped lang="scss">
.home {
  margin-top: 100px;
}
</style>

// react-client/src/views/Home.jsx
import React from 'react';

class Home extends React.Component {
  render() {
    return (
      <div className="mt-20">
        <span className="text-6xl tracking-tight font-extrabold text-gray-800">Track Your Watch Activity</span>

        <p className="text-lg text-gray-500">Start by searching for a show or movie above.</p>
      </div>
    );
  }
}

export default Home;
